title: Juan Rios
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a product designer passionate about visual design, meaningful interactions and engaging user experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https:juanrios.me"

twitter_username:   juan_nl
github_username:    riosjuan
dribbble_username:  juanrios

# Build settings
markdown: kramdown

# Sass output styles
# styles: nested, expanded, compact and compressed
sass:
  style: compressed
gems:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME

permalink: pretty

collections:
    projects:
      output: /:collection/:path/:title:output_ext

autoprefixer:
  browsers:
  - last 2 versions